### 注释 设置端口为8080
server:
  port: 8080
  
spring:
### jsp 渲染
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
### 设置单个上传文件的大小      
  servlet:
    multipart:
      max-file-size: 1MB
### 设置一次请求上传文件的总容量
      max-request-size: 4MB
      
###FREEMARKER Configuration
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: 
    - classpath:/templates/
    
### Thymeleaf Configuration
  thymeleaf:
    cache: false
    enable-spring-el-compiler: true
    encoding: UTF-8
    suffix: .html
    check-template-location: true
    check-template: true
    servlet:
      content-type: text/html; charset=utf-8
      
### datasource Configuration      
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

### Redis Configuration
  redis: 
    pool: 
      max-idle: 10
      min-idle: 5
      max-total: 20
    hostName: 127.0.0.1
    port: 6379
  
  
### hibernate Configuration
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

### mybatis Configuration   
mybatis:
  type-aliases-package: com.bean


### two datasource Configuration
mysql: 
  datasource:
    test1: 
      url: jdbc:mysql://localhost:3306/mysql
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
    test2: 
      url: jdbc:mysql://localhost:3306/mybatis
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60



    
### 自定义参数
cus:
  val: 张三
  bean: 
    id: 20
    name: 张三
  arr1: 1, 3, 4
  arr2: [1, 3, 4]
  list:
    - lista
    - listb
  map:
    a: mapa
    b: mapb
  listmap:
    - a: a
      b: b
      c: c
    - d: d
      e: e
      f: f
      
